version: "3"
services:
    hadoop-master:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                HOST_IP: 192.168.100.2
                #HOST_IP: 192.168.31.127
        hostname: hadoop-master
        image: liyi/hadoop:1.0
        container_name: hadoop-master
        network_mode: hadoop
        command: ["-d","namenode"]
        ports:
            - "50070:50070"
            - "8088:8088"
            - "50022:22"
        volumes:
            - /Users/liyi/Develop/docker-volume/files:/home/local

    hadoop-slave1:
        hostname: hadoop-slave1
        image: liyi/hadoop:1.0
        container_name: hadoop-slave1
        network_mode: hadoop
        command: ["-d","datanode"]
        depends_on:
            - hadoop-master
        volumes:
            - /Users/liyi/Develop/docker-volume/files:/home/local

    hadoop-slave2:
        hostname: hadoop-slave2
        image: liyi/hadoop:1.0
        container_name: hadoop-slave2
        network_mode: hadoop
        command: ["-d","datanode"]
        depends_on:
            - hadoop-master
        volumes:
            - /Users/liyi/Develop/docker-volume/files:/home/local
