version: "3"
services:
    mysql-dev:
        hostname: mysql-dev
        image: mysql:5.7.18
        container_name: mysql-dev
        network_mode: hadoop
        ports:
            - "3306:3306"
        volumes:
            - /Users/liyi/Develop/docker-volume/mysql-data:/var/lib/mysql 
        command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        environment:
            TZ: Asia/Shanghai
            MYSQL_ROOT_PASSWORD: 8576
            MYSQL_DATABASE: hive 
        restart: unless-stopped
