version: "3"
services:
    jdk:
        build:
            context: .
            dockerfile: Dockerfile
            args: 
                #HOST_IP: 192.168.100.2 
                HOST_IP: 192.168.31.127
        image: liyi/jdk:1.0
